services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: bolson
      MYSQL_DATABASE: dbmala  ga
      MYSQL_USER: frodo
      MYSQL_PASSWORD: bolson
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lamp_network

  php:
    image: php:8.2-apache
    container_name: php
    volumes:
      - /root/portainer/p/html:/var/www/html
    ports:
      - "80:80"
    networks:
      - lamp_network

networks:
  lamp_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
